#! /bin/sh

flameshot &
sxhkd &
picom -b &
xwallpaper --zoom ~/Pictures/Desktop\ Backgrounds/street-japan.jpg
$HOME/.config/polybar/launch.sh &

bspc monitor DP-1  -d 1 2 3 4 5
bspc monitor HDMI-2 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5624ba"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"
